module.exports = {
  // Common tech terms
  "configuration": "config",
  "configurations": "configs",
  "repository": "repo",
  "directory": "dir",
  "directories": "dirs",
  "environment": "env",
  "parameters": "params",
  "parameter": "param",
  "argument": "arg",
  "arguments": "args",
  "function": "fn",
  "functions": "fns",
  "initialize": "init",
  "initialization": "init",
  "information": "info",
  "message": "msg",
  "messages": "msgs",
  "database": "db",
  "application": "app",
  "applications": "apps",
  "temporary": "temp",
  "maximum": "max",
  "minimum": "min",
  "asynchronous": "async",
  "synchronous": "sync",
  "reference": "ref",
  "references": "refs",
  "implementation": "impl",
  "authentication": "auth",
  "authorization": "authz",
  "dependency": "dep",
  "dependencies": "deps",
  "repositories": "repos",
  "variable": "var",
  "variables": "vars",
  "string": "str",
  "integer": "int",
  "boolean": "bool",
  "request": "req",
  "response": "res",
  "error": "err",
  "errors": "errs",
  "exception": "ex",
  "exceptions": "exs",
  "documentation": "docs",
  "document": "doc",
  
  // Verbs/Actions
  "implement a solution for": "fix",
  "create a new": "make",
  "make a new": "make",
  "set up": "setup",
  "figure out": "find",
  "look into": "check",
  
  // Adjectives
  "extensive": "big",
  "massive": "huge",
  "complicated": "hard",
  "difficult": "hard",
  "straightforward": "easy",
  "simple": "easy",
  
  // Brutal/Oblivion mode extreme replacements
  "brutal_replacements": {
    "is equal to": "=",
    "equals": "=",
    "greater than": ">",
    "less than": "<",
    "and": "&",
    "or": "|",
    "with": "w/",
    "without": "w/o",
    "because": "cuz",
    "number": "#",
    "check": "chk",
    "update": "upd",
    "delete": "del",
    "remove": "rm",
    "create": "mk",
    "make": "mk"
  }
};
